Extends DLA.py. Starts rust firmware for dla.
soc-hub-fi/headsail-vp pull request #6
Opened 2024-04-16 09:26 UTC by vilukissa68

Iso PR, mutta muutokset koskevat vain DLA.py:tä ja uutta dla-driver esimerkkiä, joten ei pitäisi olla vaikutusta muualle.

2024-04-17 12:20 UTC, hegza commented
Vahva veto olisi ollut puolittaa Python ja firmware kahteen pull requestiin :P Se auttaa mm. sen kanssa ettei mun tarvii yhdeltä istumalta arvioida molempia.

2024-04-17 12:33 UTC, hegza commented
Täältä löydät hyvän esimerkin siitä miten itse olen kirjoittanut noi register access koodit mitä sullakin on tässä: https://gitlab.tuni.fi/soc-hub/bow/hw/rt-ss/-/blob/main/examples/hello_rt/src/lib.rs?ref_type=heads#L44-77

2024-04-17 13:00 UTC, hegza requested changes
Hyvältä näyttää yleisesti.

Mulla ei vielä oo hyvää hahmotusta siitä miltä Renode Peripheralin Python koodin kuuluu näyttää, niin en ottanut hirveästi kantaa muuten kuin itsestäänselviin juttuihin.

Firmwaressa on muutama selkeä kehityskohta, jotka alla.

2024-04-17 13:00 UTC, hegza commented on examples/hpc/dla-driver/.DS_Store
Tämä ei vaikuta relevantilta tiedostolta lisätä :P sen voisi poistaa puusta ja lisätä omaan ignoreen: .git/info/exclude

2024-04-17 13:00 UTC, hegza commented on examples/hpc/dla-driver/Cargo.toml
> +name = "hello-dla"
Korjaa projektin nimi: "dla-driver".

2024-04-17 13:00 UTC, hegza commented on examples/hpc/dla-driver/connect-and-load.gdb
> +# HPC is exposed at to 3335
Typo "at to". Varmaan tullut mukana copypastessa jostain muualta :P

2024-04-17 13:00 UTC, hegza commented on examples/hpc/dla-driver/src/lib.rs
> +}
Tämä taitaa löytyä jo headsail_bsp:stä. Ei kenties kannata duplikoida tänne. Jos haluat funktion näkyviin tässä moduulissa, käytä `use headsail_bsp::uart_write;`

2024-04-17 13:00 UTC, hegza commented on examples/hpc/dla-driver/src/lib.rs
> +    }
Tämän saman asian voisi ilmaista kompaktimmin näin:

```rust
unsafe { ptr::write_volatile(DLA0_addr as *mut u64, value) };
```

Eli `value.to_le_bytes()` on (kai) tässä tarpeeton, sillä arvot on oletuksena little endiania RISC-V:llä. Ja pointerilla saa valittua peräkkäisiä elementtejä pidentämällä pointerin tyyppiä.

2024-04-17 13:00 UTC, hegza commented on examples/hpc/dla-driver/src/lib.rs
> +pub fn dla_write_reg(offset: usize, value: usize) {
Tässä on haettu varmaan tyyppiä: `value: u64`. Teknisesti ovat sama, mutta merkitys on eri. `offset: usize` on tässä oikein.

2024-04-17 13:00 UTC, hegza commented on examples/hpc/dla-driver/src/lib.rs
> +pub fn dla_read_reg(offset: usize) -> usize {
Palauta `u64` kts.  yllä.

2024-04-17 13:00 UTC, hegza commented on examples/hpc/dla-driver/src/lib.rs
> +        + ((buf[3] as u32) << 24)) as usize;
Sama homma kuin yllä: pelkkä `buf` riittää tässä kaiken valitun koodin tilalle, kun tyypit ovat oikein.

2024-04-17 13:00 UTC, hegza commented on examples/hpc/dla-driver/src/lib.rs
> +    return;
Ylimääräinen `return`. Rust-funktiot palauttavat lopuksi oletuksena. Palautuksen oletustyyppi on unit type "`()`" mutta sitä ei yleensä kirjoiteta auki ja ei liene oleellista tässä.

2024-04-17 13:00 UTC, hegza commented on scripts/resc/0_mach_create.resc
> +showAnalyzer sysbus.apb_uart_0
Pidä tää muutos paikallisena vaan :P Päädytään muuten vaan committaileen tämä muutos edes taas aina kun vaihdetaan testisetupin UARTtia.

2024-04-17 13:00 UTC, hegza commented on vp/devel/common.repl
> +    size: 0x80068
Jees hyvältä näyttää.

2024-04-17 13:00 UTC, hegza commented on vp/devel/external_modules/dla_inter
Mitäs täällä tapahtuu? :D Mikä tämä tiedosto on ja mikä sen funktio on?

2024-04-17 13:00 UTC, hegza commented on vp/devel/hpc.repl
> +    size: 0x60000000
Onko niin että meillä on tämä muistin koko generoitunut väärin? Mikä on syy sille että tämän kokoa muutetaan. Asia on syytä selvittää perinpohjaisesti :)

2024-04-17 13:00 UTC, hegza commented on vp/devel/python_peripherals/DLA.py
> +def reshape_to_CWH(data):
lyhenteet snake_casessa myös pienellä `reshape_to_cwh`

2024-04-17 13:00 UTC, hegza commented on vp/devel/python_peripherals/DLA.py
> +    """Takes tensor in HWC format and reshapes it to CWH"""
Vois ehkä olla kilttiä mainita mistä lyhenteet HWC ja CWH tai muuten avata mitä tässä tehdään. Eivät ole itselleni välittömästi tuttuja vaikka pystynkin kontekstista päättelemään mistä on kyse.

2024-04-17 13:00 UTC, hegza commented on vp/devel/python_peripherals/DLA.py
> +    return round(value)
Johan on tarpeettoman oloinen funktio 😅

2024-04-17 13:00 UTC, hegza commented on vp/devel/python_peripherals/DLA.py
>  class DLA:
Käyttäisin `Dla` eikä `DLA`. Lyhenteiden kirjoittaminen koodissa capsilla aiheuttaa vaikeuksia myöhemmin ja on tyypillisesti konvention vastainen (konventiossa kuin konventiossa). Se myös vaikeuttaa koodin lukemista kun sanoilla on semanttista merkitystä.

2024-04-17 13:00 UTC, hegza commented on vp/devel/python_peripherals/DLA.py
> +class DLAMAC:
Sama täällä: käyttäisin `DlaMac`

2024-04-17 16:43 UTC, hegza commented on examples/hpc/dla-driver/src/lib.rs
> +pub fn dla_write_reg(offset: usize, value: usize) {
Itseasiassa, on siitä todellista hyötyäkin. `value: u64` toimii oikein molemmilla prosessoreilla: SysCtrl & HPC, `value: usize` toimii kuten ajattelet vain HPC:llä. Olipa oiva demonstraatio erosta.

2024-04-18 07:38 UTC, vilukissa68 commented on vp/devel/hpc.repl
> +    size: 0x60000000
Headsailin memory map dokumentissa SDRAM:in alkupisteeksi ilmoitetaan 1000_0000 ja loppupisteeksi 6FFF_FFFF. Eikös tuo tarkoita että SDRAM:in koko on 6000_0000? https://soc-hub.gitlab-pages.tuni.fi/headsail/hw/headsail/address_map.html

2024-04-18 07:53 UTC, vilukissa68 commented on examples/hpc/dla-driver/.DS_Store
Tämän pitäisi olla nyt poistettu

2024-04-18 07:54 UTC, vilukissa68 commented on examples/hpc/dla-driver/Cargo.toml
> +name = "hello-dla"
Nimi korjattu

2024-04-18 07:54 UTC, vilukissa68 commented on examples/hpc/dla-driver/connect-and-load.gdb
> +# HPC is exposed at to 3335
Typo korjattu

2024-04-18 07:54 UTC, vilukissa68 commented on examples/hpc/dla-driver/src/lib.rs
> +}
Duplikaatti poistettu

2024-04-18 07:56 UTC, vilukissa68 commented on examples/hpc/dla-driver/src/lib.rs
> +    }
dla_write_reg() ja dla_read_reg() on tarkoitettu DLA:n "rekisterien" lukemiseen, jotka ovat ainakin dokumentaation mukaan 32bittisiä. Otin käyttöön tuon kompaktin tyylin, mutta u64 sijasta käytän u32.

2024-04-18 07:57 UTC, vilukissa68 commented on examples/hpc/dla-driver/src/lib.rs
> +pub fn dla_write_reg(offset: usize, value: usize) {
Sama kuin tuossa ylempänä. `value: usize` -> `value: u32`.

2024-04-18 07:58 UTC, vilukissa68 commented on examples/hpc/dla-driver/src/lib.rs
> +pub fn dla_read_reg(offset: usize) -> usize {
Yllä mainitun mukaisesti palautetaan u32.

2024-04-18 07:59 UTC, vilukissa68 commented on examples/hpc/dla-driver/src/lib.rs
> +        + ((buf[3] as u32) << 24)) as usize;
Tästä riippuvaiset tyypit korjattu ja funktio siistitty.

2024-04-18 07:59 UTC, vilukissa68 commented on examples/hpc/dla-driver/src/lib.rs
> +    return;
`return` poistettu

2024-04-18 08:00 UTC, vilukissa68 commented on scripts/resc/0_mach_create.resc
> +showAnalyzer sysbus.apb_uart_0
Muutos peruutettu.

2024-04-18 08:01 UTC, vilukissa68 commented on vp/devel/external_modules/dla_inter
Hups. Ulkoisen python moduulin testailussa käytetty välitystiedosto jäänyt kummittelemaan. Pitäisi olla nyt poistettu.

2024-04-18 08:02 UTC, vilukissa68 commented on vp/devel/python_peripherals/DLA.py
> +def reshape_to_CWH(data):
snake_case korjattu

2024-04-18 08:02 UTC, vilukissa68 commented on vp/devel/python_peripherals/DLA.py
> +    """Takes tensor in HWC format and reshapes it to CWH"""
Lyhenteet avattu

2024-04-18 08:05 UTC, vilukissa68 commented on vp/devel/python_peripherals/DLA.py
> +    return round(value)
En ole ihan perillä siitä miten DLA:n pyöristys toimii, joten jätin tämän placeholderiksi.

2024-04-18 08:05 UTC, vilukissa68 commented on vp/devel/python_peripherals/DLA.py
>  class DLA:
Luokan nimi korjattu

2024-04-18 08:06 UTC, vilukissa68 commented on vp/devel/python_peripherals/DLA.py
> +class DLAMAC:
Luokan nimi korjattu

2024-04-18 08:15 UTC, hegza commented on examples/hpc/dla-driver/src/lib.rs
> +    }
Joo, juuri näin.

2024-04-18 08:18 UTC, hegza commented on vp/devel/hpc.repl
> +    size: 0x60000000
Joo näin on. Pidän todennäköisimpänä että olen itse tehnyt tuohon jonkun virhekorjauksen. Tämä on oikein miten laitoit.

2024-04-18 08:37 UTC, hegza commented on vp/devel/python_peripherals/DLA.py
> +    return round(value)
Hyväksytään

2024-04-18 08:47 UTC, closed without merging